behaviors:
  Air-to-Air Combat:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 16384
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.225
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.998

      curiosity:
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.00015

    keep_checkpoints: 20
    max_steps: 25000000
    checkpoint_interval: 1000000
    time_horizon: 1024
    summary_freq: 16384

    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 5000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
