behaviors:
  Learn to fly:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.05
      epsilon: 0.2
      lambd: 0.925
      num_epoch: 5
      learning_rate_schedule: linear
      epsilon_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.995

      curiosity:
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003

      gail:
        gamma: 0.995
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.0003
        use_actions: false
        use_vail: false
        demo_path: "Demos/LearnToFly.demo"

    behavioral_cloning:
      steps: 1000000
      strength: 1.0
      samples_per_update: 0
      demo_path: "Demos/LearnToFly.demo"

    keep_checkpoints: 20
    max_steps: 15000000
    checkpoint_interval: 1000000
    time_horizon: 2048
    summary_freq: 4096
