behaviors:
  Air-to-Air Combat:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 262144
      learning_rate: 0.0001
      beta: 0.003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 256

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.9975

      curiosity:
        strength: 0.05
        gamma: 0.9975
        encoding_size: 256
        learning_rate: 3.0e-4

    #   gail:
    #     strength: 0.05
    #     gamma: 0.9975
    #     demo_path: "Demos/CombatDemo.demo"

    # behavioral_cloning:
    #   strength: 0.05
    #   gamma: 0.9975
    #   demo_path: "Demos/CombatDemo.demo"

    keep_checkpoints: 20
    max_steps: 30000000
    checkpoint_interval: 100000
    time_horizon: 128
    summary_freq: 10000

    self_play:
      window: 30
      save_steps: 100000
      swap_steps: 50000
      team_change: 500000
      play_against_latest_model_ratio: 0.5
